// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchBaseDirectory():Promise<string>;

export function SayHello():Promise<void>;

export function StartDownload(arg1:string,arg2:number,arg3:string,arg4:boolean):Promise<void>;
